// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/settotp/definition.proto

package settotp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SetTotpService_SetTotp_FullMethodName = "/settotp.SetTotpService/SetTotp"
)

// SetTotpServiceClient is the client API for SetTotpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SetTotpServiceClient interface {
	SetTotp(ctx context.Context, in *SetTotpRequest, opts ...grpc.CallOption) (*SetTotpResponse, error)
}

type setTotpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSetTotpServiceClient(cc grpc.ClientConnInterface) SetTotpServiceClient {
	return &setTotpServiceClient{cc}
}

func (c *setTotpServiceClient) SetTotp(ctx context.Context, in *SetTotpRequest, opts ...grpc.CallOption) (*SetTotpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTotpResponse)
	err := c.cc.Invoke(ctx, SetTotpService_SetTotp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SetTotpServiceServer is the server API for SetTotpService service.
// All implementations must embed UnimplementedSetTotpServiceServer
// for forward compatibility.
type SetTotpServiceServer interface {
	SetTotp(context.Context, *SetTotpRequest) (*SetTotpResponse, error)
	mustEmbedUnimplementedSetTotpServiceServer()
}

// UnimplementedSetTotpServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSetTotpServiceServer struct{}

func (UnimplementedSetTotpServiceServer) SetTotp(context.Context, *SetTotpRequest) (*SetTotpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTotp not implemented")
}
func (UnimplementedSetTotpServiceServer) mustEmbedUnimplementedSetTotpServiceServer() {}
func (UnimplementedSetTotpServiceServer) testEmbeddedByValue()                        {}

// UnsafeSetTotpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SetTotpServiceServer will
// result in compilation errors.
type UnsafeSetTotpServiceServer interface {
	mustEmbedUnimplementedSetTotpServiceServer()
}

func RegisterSetTotpServiceServer(s grpc.ServiceRegistrar, srv SetTotpServiceServer) {
	// If the following call pancis, it indicates UnimplementedSetTotpServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SetTotpService_ServiceDesc, srv)
}

func _SetTotpService_SetTotp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTotpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetTotpServiceServer).SetTotp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetTotpService_SetTotp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetTotpServiceServer).SetTotp(ctx, req.(*SetTotpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SetTotpService_ServiceDesc is the grpc.ServiceDesc for SetTotpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SetTotpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "settotp.SetTotpService",
	HandlerType: (*SetTotpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetTotp",
			Handler:    _SetTotpService_SetTotp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/settotp/definition.proto",
}
