// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/mailtouid/definition.proto

package mailtouid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailToUidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mail          string                 `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailToUidRequest) Reset() {
	*x = MailToUidRequest{}
	mi := &file_proto_mailtouid_definition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailToUidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailToUidRequest) ProtoMessage() {}

func (x *MailToUidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mailtouid_definition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailToUidRequest.ProtoReflect.Descriptor instead.
func (*MailToUidRequest) Descriptor() ([]byte, []int) {
	return file_proto_mailtouid_definition_proto_rawDescGZIP(), []int{0}
}

func (x *MailToUidRequest) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

type MailToUidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailToUidResponse) Reset() {
	*x = MailToUidResponse{}
	mi := &file_proto_mailtouid_definition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailToUidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailToUidResponse) ProtoMessage() {}

func (x *MailToUidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mailtouid_definition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailToUidResponse.ProtoReflect.Descriptor instead.
func (*MailToUidResponse) Descriptor() ([]byte, []int) {
	return file_proto_mailtouid_definition_proto_rawDescGZIP(), []int{1}
}

func (x *MailToUidResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

var File_proto_mailtouid_definition_proto protoreflect.FileDescriptor

const file_proto_mailtouid_definition_proto_rawDesc = "" +
	"\n" +
	" proto/mailtouid/definition.proto\x12\tmailtouid\"&\n" +
	"\x10MailToUidRequest\x12\x12\n" +
	"\x04mail\x18\x01 \x01(\tR\x04mail\"%\n" +
	"\x11MailToUidResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid2Z\n" +
	"\x10MailToUidService\x12F\n" +
	"\tMailToUid\x12\x1b.mailtouid.MailToUidRequest\x1a\x1c.mailtouid.MailToUidResponseB\x1bZ\x19proto/mailtouid;mailtouidb\x06proto3"

var (
	file_proto_mailtouid_definition_proto_rawDescOnce sync.Once
	file_proto_mailtouid_definition_proto_rawDescData []byte
)

func file_proto_mailtouid_definition_proto_rawDescGZIP() []byte {
	file_proto_mailtouid_definition_proto_rawDescOnce.Do(func() {
		file_proto_mailtouid_definition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mailtouid_definition_proto_rawDesc), len(file_proto_mailtouid_definition_proto_rawDesc)))
	})
	return file_proto_mailtouid_definition_proto_rawDescData
}

var file_proto_mailtouid_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_mailtouid_definition_proto_goTypes = []any{
	(*MailToUidRequest)(nil),  // 0: mailtouid.MailToUidRequest
	(*MailToUidResponse)(nil), // 1: mailtouid.MailToUidResponse
}
var file_proto_mailtouid_definition_proto_depIdxs = []int32{
	0, // 0: mailtouid.MailToUidService.MailToUid:input_type -> mailtouid.MailToUidRequest
	1, // 1: mailtouid.MailToUidService.MailToUid:output_type -> mailtouid.MailToUidResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mailtouid_definition_proto_init() }
func file_proto_mailtouid_definition_proto_init() {
	if File_proto_mailtouid_definition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mailtouid_definition_proto_rawDesc), len(file_proto_mailtouid_definition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mailtouid_definition_proto_goTypes,
		DependencyIndexes: file_proto_mailtouid_definition_proto_depIdxs,
		MessageInfos:      file_proto_mailtouid_definition_proto_msgTypes,
	}.Build()
	File_proto_mailtouid_definition_proto = out.File
	file_proto_mailtouid_definition_proto_goTypes = nil
	file_proto_mailtouid_definition_proto_depIdxs = nil
}
